// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: PlayerData.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace Proto.Server
{

    [global::ProtoBuf.ProtoContract()]
    public partial class PlayerBasicData : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"level")]
        public uint Level { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"exp")]
        public uint Exp { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"nickname")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Nickname { get; set; } = "";

        [global::ProtoBuf.ProtoMember(4, Name = @"login_times")]
        public uint LoginTimes { get; set; }

        [global::ProtoBuf.ProtoMember(5, Name = @"world_level")]
        public uint WorldLevel { get; set; }

        [global::ProtoBuf.ProtoMember(6, Name = @"stamina")]
        public uint Stamina { get; set; }

        [global::ProtoBuf.ProtoMember(7, Name = @"created_timestamp")]
        public ulong CreatedTimestamp { get; set; }

        [global::ProtoBuf.ProtoMember(8, Name = @"last_login_timestamp")]
        public ulong LastLoginTimestamp { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class AvatarSkillTreeData : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"point_id")]
        public uint PointId { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"level")]
        public uint Level { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class PathInfo : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"path_id")]
        public uint PathId { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"rank")]
        public uint Rank { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"equipment_unique_id")]
        public uint EquipmentUniqueId { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"relic_maps")]
        [global::ProtoBuf.ProtoMap]
        public global::System.Collections.Generic.Dictionary<uint, uint> RelicMaps { get; } = new global::System.Collections.Generic.Dictionary<uint, uint>();

        [global::ProtoBuf.ProtoMember(5, Name = @"skill_tree_list")]
        public global::System.Collections.Generic.List<AvatarSkillTreeData> SkillTreeLists { get; } = new global::System.Collections.Generic.List<AvatarSkillTreeData>();

        [global::ProtoBuf.ProtoMember(6, Name = @"skin")]
        public uint Skin { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class AvatarData : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"avatar_type")]
        public int AvatarType { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"avatar_id")]
        public uint AvatarId { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"level")]
        public uint Level { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"exp")]
        public uint Exp { get; set; }

        [global::ProtoBuf.ProtoMember(5, Name = @"promotion")]
        public uint Promotion { get; set; }

        [global::ProtoBuf.ProtoMember(6, Name = @"rank")]
        public uint Rank { get; set; }

        [global::ProtoBuf.ProtoMember(7, Name = @"first_met_time_stamp")]
        public ulong FirstMetTimeStamp { get; set; }

        [global::ProtoBuf.ProtoMember(8, Name = @"skill_tree_list")]
        public global::System.Collections.Generic.List<AvatarSkillTreeData> SkillTreeLists { get; } = new global::System.Collections.Generic.List<AvatarSkillTreeData>();

        [global::ProtoBuf.ProtoMember(9, Name = @"equipment_unique_id")]
        public uint EquipmentUniqueId { get; set; }

        [global::ProtoBuf.ProtoMember(10, Name = @"relic_maps")]
        [global::ProtoBuf.ProtoMap]
        public global::System.Collections.Generic.Dictionary<uint, uint> RelicMaps { get; } = new global::System.Collections.Generic.Dictionary<uint, uint>();

        [global::ProtoBuf.ProtoMember(11, Name = @"path_infoes")]
        [global::ProtoBuf.ProtoMap]
        public global::System.Collections.Generic.Dictionary<uint, PathInfo> PathInfoes { get; } = new global::System.Collections.Generic.Dictionary<uint, PathInfo>();

        [global::ProtoBuf.ProtoMember(12, Name = @"skin")]
        public uint Skin { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class PlayerAvatarData : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"avatar_list")]
        public global::System.Collections.Generic.List<AvatarData> AvatarLists { get; } = new global::System.Collections.Generic.List<AvatarData>();

        [global::ProtoBuf.ProtoMember(2, Name = @"trailblazer_gender")]
        public uint TrailblazerGender { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"basic_type")]
        public uint BasicType { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"mar7th_type")]
        public uint Mar7thType { get; set; }

        [global::ProtoBuf.ProtoMember(5, Name = @"unlock_skin", IsPacked = true)]
        public uint[] UnlockSkins { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class LineupAvatarData : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"avatar_id")]
        public uint AvatarId { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"avatar_type")]
        public int AvatarType { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"slot")]
        public uint Slot { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"hp")]
        public uint Hp { get; set; }

        [global::ProtoBuf.ProtoMember(5, Name = @"sp")]
        public uint Sp { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class LineupData : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"avatar_lists")]
        public global::System.Collections.Generic.List<LineupAvatarData> AvatarLists { get; } = new global::System.Collections.Generic.List<LineupAvatarData>();

        [global::ProtoBuf.ProtoMember(2, Name = @"index")]
        public uint Index { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"leader_slot")]
        public uint LeaderSlot { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"name")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Name { get; set; } = "";

        [global::ProtoBuf.ProtoMember(5, Name = @"is_virtual")]
        public bool IsVirtual { get; set; }

        [global::ProtoBuf.ProtoMember(6, Name = @"plane_id")]
        public uint PlaneId { get; set; }

        [global::ProtoBuf.ProtoMember(7, Name = @"extra_lineup_type")]
        public int ExtraLineupType { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class PlayerLineupData : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"lineup_list")]
        public global::System.Collections.Generic.List<LineupData> LineupLists { get; } = new global::System.Collections.Generic.List<LineupData>();

        [global::ProtoBuf.ProtoMember(2, Name = @"cur_lineup_index")]
        public uint CurLineupIndex { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"mp")]
        public uint Mp { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"mp_max")]
        public uint MpMax { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class EquipmentData : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"unique_id")]
        public uint UniqueId { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"tid")]
        public uint Tid { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"level")]
        public uint Level { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"exp")]
        public uint Exp { get; set; }

        [global::ProtoBuf.ProtoMember(5, Name = @"promotion")]
        public uint Promotion { get; set; }

        [global::ProtoBuf.ProtoMember(6, Name = @"rank")]
        public uint Rank { get; set; }

        [global::ProtoBuf.ProtoMember(7, Name = @"avatar_id")]
        public uint AvatarId { get; set; }

        [global::ProtoBuf.ProtoMember(8, Name = @"is_protected")]
        public bool IsProtected { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class MaterialData : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"tid")]
        public uint Tid { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"num")]
        public uint Num { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class RelicAffixData : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"affix_id")]
        public uint AffixId { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"cnt")]
        public uint Cnt { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"step")]
        public uint Step { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class RelicData : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"unique_id")]
        public uint UniqueId { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"tid")]
        public uint Tid { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"level")]
        public uint Level { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"exp")]
        public uint Exp { get; set; }

        [global::ProtoBuf.ProtoMember(5, Name = @"avatar_id")]
        public uint AvatarId { get; set; }

        [global::ProtoBuf.ProtoMember(6, Name = @"main_affix_id")]
        public uint MainAffixId { get; set; }

        [global::ProtoBuf.ProtoMember(7, Name = @"sub_affix_lists")]
        public global::System.Collections.Generic.List<RelicAffixData> SubAffixLists { get; } = new global::System.Collections.Generic.List<RelicAffixData>();

        [global::ProtoBuf.ProtoMember(8, Name = @"is_protected")]
        public bool IsProtected { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class PlayerItemData : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"uid_counter")]
        public uint UidCounter { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"equipment_lists")]
        public global::System.Collections.Generic.List<EquipmentData> EquipmentLists { get; } = new global::System.Collections.Generic.List<EquipmentData>();

        [global::ProtoBuf.ProtoMember(3, Name = @"material_lists")]
        public global::System.Collections.Generic.List<MaterialData> MaterialLists { get; } = new global::System.Collections.Generic.List<MaterialData>();

        [global::ProtoBuf.ProtoMember(4, Name = @"relic_lists")]
        public global::System.Collections.Generic.List<RelicData> RelicLists { get; } = new global::System.Collections.Generic.List<RelicData>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class VectorData : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"x", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
        public int X { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"y", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
        public int Y { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"z", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
        public int Z { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class PlayerSceneData : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"pos")]
        public VectorData Pos { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"rot")]
        public VectorData Rot { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"plane_id")]
        public uint PlaneId { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"floor_id")]
        public uint FloorId { get; set; }

        [global::ProtoBuf.ProtoMember(5, Name = @"entry_id")]
        public uint EntryId { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class PlayerData : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"basic_comp_data")]
        public PlayerBasicData BasicCompData { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"avatar_comp_data")]
        public PlayerAvatarData AvatarCompData { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"lineup_comp_data")]
        public PlayerLineupData LineupCompData { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"item_comp_data")]
        public PlayerItemData ItemCompData { get; set; }

        [global::ProtoBuf.ProtoMember(5, Name = @"scene_comp_data")]
        public PlayerSceneData SceneCompData { get; set; }

    }

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
