using Proto;

namespace GameServer.Network
{
    internal class DummyPacket
    {
        private static readonly Dictionary<CmdId, CmdId> RequestResponseMapping = new Dictionary<CmdId, CmdId>()
        {
            { CmdId.CmdGetFirstTalkNpcCsReq, CmdId.CmdGetFirstTalkNpcScRsp },
            { CmdId.CmdRogueMagicQueryCsReq, CmdId.CmdRogueMagicQueryScRsp },
            { CmdId.CmdPlayerLoginFinishCsReq, CmdId.CmdPlayerLoginFinishScRsp },
            { CmdId.CmdRogueTournGetCurRogueCocoonInfoCsReq, CmdId.CmdRogueTournGetCurRogueCocoonInfoScRsp },
            { CmdId.CmdUnlockTutorialGuideCsReq, CmdId.CmdUnlockTutorialGuideScRsp },
            { CmdId.CmdGetRechargeGiftInfoCsReq, CmdId.CmdGetRechargeGiftInfoScRsp },
            { CmdId.CmdGetRechargeBenefitInfoCsReq, CmdId.CmdGetRechargeBenefitInfoScRsp },
            { CmdId.CmdGetRogueCommonDialogueDataCsReq, CmdId.CmdGetRogueCommonDialogueDataScRsp },
            { CmdId.CmdGetRogueInfoCsReq, CmdId.CmdGetRogueInfoScRsp },
            { CmdId.CmdGetRogueHandbookDataCsReq, CmdId.CmdGetRogueHandbookDataScRsp },
            { CmdId.CmdGetRogueEndlessActivityDataCsReq, CmdId.CmdGetRogueEndlessActivityDataScRsp },
            { CmdId.CmdChessRogueQueryCsReq, CmdId.CmdChessRogueQueryScRsp },
            { CmdId.CmdRogueTournQueryCsReq, CmdId.CmdRogueTournQueryScRsp },
            { CmdId.CmdGetRogueCollectionCsReq, CmdId.CmdGetRogueCollectionScRsp },
            { CmdId.CmdGetRogueExhibitionCsReq, CmdId.CmdGetRogueExhibitionScRsp },
            { CmdId.CmdGetChessRogueNousStoryInfoCsReq, CmdId.CmdGetChessRogueNousStoryInfoScRsp },
            { CmdId.CmdCommonRogueQueryCsReq, CmdId.CmdCommonRogueQueryScRsp },
            { CmdId.CmdGetRogueScoreRewardInfoCsReq, CmdId.CmdGetRogueScoreRewardInfoScRsp },
            { CmdId.CmdRogueArcadeGetInfoCsReq, CmdId.CmdRogueArcadeGetInfoScRsp },
            { CmdId.CmdGetBagCsReq, CmdId.CmdGetBagScRsp },
            { CmdId.CmdGetMarkItemListCsReq, CmdId.CmdGetMarkItemListScRsp},
            { CmdId.CmdGetPlayerBoardDataCsReq, CmdId.CmdGetPlayerBoardDataScRsp},
            { CmdId.CmdGetCurAssistCsReq, CmdId.CmdGetCurAssistScRsp },
            { CmdId.CmdGetAllLineupDataCsReq, CmdId.CmdGetAllLineupDataScRsp },
            { CmdId.CmdGetAllServerPrefsDataCsReq, CmdId.CmdGetAllServerPrefsDataScRsp },
            { CmdId.CmdGetMissionDataCsReq, CmdId.CmdGetMissionDataScRsp },
            { CmdId.CmdGetQuestDataCsReq, CmdId.CmdGetQuestDataScRsp },
            { CmdId.CmdDailyFirstMeetPamCsReq, CmdId.CmdDailyFirstMeetPamScRsp },
            { CmdId.CmdGetBattleCollegeDataCsReq, CmdId.CmdGetBattleCollegeDataScRsp },
            { CmdId.CmdGetNpcStatusCsReq, CmdId.CmdGetNpcStatusScRsp },
            { CmdId.CmdGetSecretKeyInfoCsReq, CmdId.CmdGetSecretKeyInfoScRsp },
            { CmdId.CmdGetHeartDialInfoCsReq, CmdId.CmdGetHeartDialInfoScRsp },
            { CmdId.CmdGetVideoVersionKeyCsReq, CmdId.CmdGetVideoVersionKeyScRsp },
            { CmdId.CmdHeliobusActivityDataCsReq, CmdId.CmdHeliobusActivityDataScRsp },
            { CmdId.CmdGetAetherDivideInfoCsReq, CmdId.CmdGetAetherDivideInfoScRsp },
            { CmdId.CmdGetMapRotationDataCsReq, CmdId.CmdGetMapRotationDataScRsp },
            { CmdId.CmdPlayerReturnInfoQueryCsReq, CmdId.CmdPlayerReturnInfoQueryScRsp },
            { CmdId.CmdGetLevelRewardTakenListCsReq, CmdId.CmdGetLevelRewardTakenListScRsp },
            { CmdId.CmdGetMainMissionCustomValueCsReq, CmdId.CmdGetMainMissionCustomValueScRsp },
            { CmdId.CmdGetMaterialSubmitActivityDataCsReq, CmdId.CmdGetMaterialSubmitActivityDataScRsp },
            { CmdId.CmdMusicRhythmDataCsReq, CmdId.CmdMusicRhythmDataScRsp },
            { CmdId.CmdGetFriendApplyListInfoCsReq, CmdId.CmdGetFriendApplyListInfoScRsp },
            { CmdId.CmdGetChatFriendHistoryCsReq, CmdId.CmdGetChatFriendHistoryScRsp },
            { CmdId.CmdGetFriendLoginInfoCsReq, CmdId.CmdGetFriendLoginInfoScRsp },
            { CmdId.CmdGetFriendBattleRecordDetailCsReq, CmdId.CmdGetFriendBattleRecordDetailScRsp },
            { CmdId.CmdGetFriendDevelopmentInfoCsReq, CmdId.CmdGetFriendDevelopmentInfoScRsp },
            { CmdId.CmdGetFriendRecommendListInfoCsReq, CmdId.CmdGetFriendRecommendListInfoScRsp },
            { CmdId.CmdSwitchHandDataCsReq, CmdId.CmdSwitchHandDataScRsp },
            { CmdId.CmdGetMissionMessageInfoCsReq, CmdId.CmdGetMissionMessageInfoScRsp },
            { CmdId.CmdTrainPartyGetDataCsReq, CmdId.CmdTrainPartyGetDataScRsp },
            { CmdId.CmdQueryProductInfoCsReq, CmdId.CmdQueryProductInfoScRsp },
            { CmdId.CmdGetPamSkinDataCsReq, CmdId.CmdGetPamSkinDataScRsp },
            { CmdId.CmdGetQuestRecordCsReq, CmdId.CmdGetQuestRecordScRsp },
            { CmdId.CmdGetDailyActiveInfoCsReq, CmdId.CmdGetDailyActiveInfoScRsp },
            { CmdId.CmdGetFightActivityDataCsReq, CmdId.CmdGetFightActivityDataScRsp },
            { CmdId.CmdGetStarFightDataCsReq, CmdId.CmdGetStarFightDataScRsp },
            { CmdId.CmdGetMultipleDropInfoCsReq, CmdId.CmdGetMultipleDropInfoScRsp },
            { CmdId.CmdGetPlayerReturnMultiDropInfoCsReq, CmdId.CmdGetPlayerReturnMultiDropInfoScRsp },
            { CmdId.CmdGetShareDataCsReq, CmdId.CmdGetShareDataScRsp },
            { CmdId.CmdGetTreasureDungeonActivityDataCsReq, CmdId.CmdGetTreasureDungeonActivityDataScRsp },
            { CmdId.CmdEvolveBuildQueryInfoCsReq, CmdId.CmdEvolveBuildQueryInfoScRsp },
            { CmdId.CmdGetAlleyInfoCsReq, CmdId.CmdGetAlleyInfoScRsp },
            { CmdId.CmdGetAetherDivideChallengeInfoCsReq, CmdId.CmdGetAetherDivideChallengeInfoScRsp },
            { CmdId.CmdGetStrongChallengeActivityDataCsReq, CmdId.CmdGetStrongChallengeActivityDataScRsp },
            { CmdId.CmdGetOfferingInfoCsReq, CmdId.CmdGetOfferingInfoScRsp },
            { CmdId.CmdClockParkGetInfoCsReq, CmdId.CmdClockParkGetInfoScRsp },
            { CmdId.CmdGetGunPlayDataCsReq, CmdId.CmdGetGunPlayDataScRsp },
            { CmdId.CmdGetTrackPhotoActivityDataCsReq, CmdId.CmdGetTrackPhotoActivityDataScRsp },
            { CmdId.CmdGetSwordTrainingDataCsReq, CmdId.CmdGetSwordTrainingDataScRsp },
            { CmdId.CmdGetFightFestDataCsReq, CmdId.CmdGetFightFestDataScRsp },
            { CmdId.CmdDifficultyAdjustmentGetDataCsReq, CmdId.CmdDifficultyAdjustmentGetDataScRsp },
            { CmdId.CmdSpaceZooDataCsReq, CmdId.CmdSpaceZooDataScRsp },
            { CmdId.CmdGetExpeditionDataCsReq, CmdId.CmdGetExpeditionDataScRsp },
            { CmdId.CmdTravelBrochureGetDataCsReq, CmdId.CmdTravelBrochureGetDataScRsp },
            { CmdId.CmdRaidCollectionDataCsReq, CmdId.CmdRaidCollectionDataScRsp },
            { CmdId.CmdGetRaidInfoCsReq, CmdId.CmdGetRaidInfoScRsp },
            { CmdId.CmdGetLoginActivityCsReq, CmdId.CmdGetLoginActivityScRsp },
            { CmdId.CmdGetTrialActivityDataCsReq, CmdId.CmdGetTrialActivityDataScRsp },
            { CmdId.CmdGetJukeboxDataCsReq, CmdId.CmdGetJukeboxDataScRsp },
            { CmdId.CmdGetMuseumInfoCsReq, CmdId.CmdGetMuseumInfoScRsp },
            { CmdId.CmdGetTelevisionActivityDataCsReq, CmdId.CmdGetTelevisionActivityDataScRsp },
            { CmdId.CmdGetTrainVisitorRegisterCsReq, CmdId.CmdGetTrainVisitorRegisterScRsp },
            { CmdId.CmdGetBoxingClubInfoCsReq, CmdId.CmdGetBoxingClubInfoScRsp },
            { CmdId.CmdTextJoinQueryCsReq, CmdId.CmdTextJoinQueryScRsp },
            { CmdId.CmdGetLoginChatInfoCsReq, CmdId.CmdGetLoginChatInfoScRsp },
            { CmdId.CmdGetFeverTimeActivityDataCsReq, CmdId.CmdGetFeverTimeActivityDataScRsp },
            { CmdId.CmdGetSummonActivityDataCsReq, CmdId.CmdGetSummonActivityDataScRsp },
            { CmdId.CmdTarotBookGetDataCsReq, CmdId.CmdTarotBookGetDataScRsp },
            { CmdId.CmdGetMarkChestCsReq, CmdId.CmdGetMarkChestScRsp },
            { CmdId.CmdMatchThreeGetDataCsReq, CmdId.CmdMatchThreeGetDataScRsp },
            { CmdId.CmdUpdateTrackMainMissionIdCsReq, CmdId.CmdUpdateTrackMainMissionIdScRsp },
            { CmdId.CmdGetNpcMessageGroupCsReq, CmdId.CmdGetNpcMessageGroupScRsp },
            { CmdId.CmdGetAllSaveRaidCsReq, CmdId.CmdGetAllSaveRaidScRsp },
            { CmdId.CmdGetAssistHistoryCsReq, CmdId.CmdGetAssistHistoryScRsp },
            { CmdId.CmdGetPlayerDetailInfoCsReq, CmdId.CmdGetPlayerDetailInfoScRsp },
            { CmdId.CmdGetEraFlipperDataCsReq, CmdId.CmdGetEraFlipperDataScRsp },
            { CmdId.CmdGetPreAvatarListCsReq, CmdId.CmdGetPreAvatarListScRsp },
            { CmdId.CmdRelicSmartWearGetPlanCsReq, CmdId.CmdRelicSmartWearGetPlanScRsp },
            { CmdId.CmdRelicSmartWearGetPinRelicCsReq, CmdId.CmdRelicSmartWearGetPinRelicScRsp },
            { CmdId.CmdSetGrowthTargetAvatarCsReq, CmdId.CmdSetGrowthTargetAvatarScRsp },
        };

        public static void Handler(GameSession session, uint req)
        {
            if (RequestResponseMapping.TryGetValue((CmdId)req, out CmdId rsp))
            {
                session.Send(NetPacket.Create(rsp));
            }
        }
    }
}
